# Generated by Django 3.1.3 on 2020-11-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='address_line_2',
        ),
    ]
