# Generated by Django 3.1.3 on 2021-03-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='article_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
