# Generated by Django 3.2.4 on 2021-06-09 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productitem_product_group'),
        ('orders', '0003_alter_orderitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productitem'),
        ),
    ]
