# Generated by Django 3.1.3 on 2021-03-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('request', 'Aangevraagd'), ('pending', 'In afwachting'), ('finished', 'Gereed')], default='requested', max_length=10),
        ),
    ]
