# Generated by Django 3.1.3 on 2021-03-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210314_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('requested', 'Aangevraagd'), ('pending', 'In afwachting'), ('finished', 'Gereed')], default='requested', max_length=10),
        ),
    ]
