# Generated by Django 3.2.4 on 2021-06-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210609_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_id',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
