# Generated by Django 3.2.4 on 2021-06-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_orderitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='article_desc',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
