# Generated by Django 3.2.4 on 2021-06-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitem_article_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
