# Generated by Django 3.2.4 on 2021-06-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rename_item_orderitem_itemm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='article_id',
            new_name='filemaker_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='article_desc',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
