# Generated by Django 3.2.4 on 2021-06-09 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20210609_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='article_id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='filemaker_id',
            new_name='fileMaker_id',
        ),
    ]
