# Generated by Django 3.2.4 on 2021-06-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20210609_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
