# Generated by Django 3.2.4 on 2021-06-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderitem_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_id',
        ),
    ]
