# Generated by Django 3.2.4 on 2021-06-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_orderitem_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='description',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
