# Generated by Django 3.1.3 on 2020-11-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productcode', models.CharField(max_length=5)),
                ('productname', models.CharField(max_length=25)),
                ('product_type', models.CharField(max_length=25)),
                ('group', models.CharField(max_length=25)),
                ('price_basis', models.CharField(max_length=15)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
