# Generated by Django 3.1.3 on 2021-03-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='image',
            field=models.FileField(blank=True, default='articles/no_image.svg', null=True, upload_to=''),
        ),
    ]
