# Generated by Django 3.1.3 on 2021-03-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210308_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='image',
            field=models.ImageField(blank=True, default='no_image.svg', upload_to='articles'),
        ),
    ]
