# Generated by Django 3.1.3 on 2020-12-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201206_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
