# Generated by Django 3.2.4 on 2021-06-09 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210412_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='product_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.productgroup'),
        ),
    ]
