# Generated by Django 3.2.4 on 2021-06-09 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productitem_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='product_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productgroup'),
        ),
    ]
