# Generated by Django 3.1.3 on 2021-03-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210308_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='image',
            field=models.FileField(blank=True, default='no_image.svg', upload_to='articles'),
        ),
    ]
