# Generated by Django 3.1.3 on 2020-11-17 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='description',
        ),
        migrations.AddField(
            model_name='productitem',
            name='product_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
