# Generated by Django 3.1.3 on 2021-01-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210122_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='slug',
            field=models.SlugField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
