# Generated by Django 3.1.3 on 2020-11-18 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201118_0807'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductItemGroup',
            new_name='ItemGroup',
        ),
        migrations.RenameField(
            model_name='productitem',
            old_name='tag',
            new_name='group',
        ),
    ]
