# Generated by Django 3.1.3 on 2020-11-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201118_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgroup',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
