# Generated by Django 3.1.3 on 2021-03-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210308_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='product_id',
            field=models.IntegerField(default=0, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
