# Generated by Django 3.1.3 on 2020-11-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201118_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
