# Generated by Django 3.1.3 on 2021-03-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210308_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='product_id',
            field=models.IntegerField(max_length=8, unique=True),
        ),
    ]
