# Generated by Django 3.1.3 on 2020-11-18 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productitem_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productitem',
            options={'ordering': ['name', 'size', 'price']},
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='total',
        ),
    ]
