# Generated by Django 3.1.3 on 2020-11-18 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20201118_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='slug',
            new_name='serial',
        ),
    ]
