# Generated by Django 3.1.3 on 2021-03-09 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210308_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='product_id',
            new_name='article_id',
        ),
    ]
