# Generated by Django 3.1.3 on 2020-11-18 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20201118_0934'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductGroup',
        ),
    ]
