# Generated by Django 3.1.3 on 2020-11-18 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20201118_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='productgroup',
            name='price_basis',
        ),
        migrations.RemoveField(
            model_name='productgroup',
            name='product_type',
        ),
    ]
