# Generated by Django 3.1.3 on 2020-11-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20201118_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgroup',
            old_name='logo',
            new_name='image',
        ),
    ]
