# Generated by Django 3.1.3 on 2020-11-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20201118_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='group',
            new_name='item_group',
        ),
    ]
